{$APP_URL} {
    root * /var/www/public
    encode zstd br gzip

    php_server

    reverse_proxy /app/* reverb:6001

    redir /mailpit /mailpit/
    handle_path /mailpit/* {
        rewrite * /mailpit{path}
        reverse_proxy mailpit:8025
    }

    tls internal
}
