version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
    groups:
      composer:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      commitlint:
        patterns:
          - "@commitlint/*"
        update-types:
          - "major"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"
        update-types:
          - "major"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "primevue"
      - dependency-name: "@primevue/*"
      - dependency-name: "@primeuix/*"
      - dependency-name: "playwright"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
