workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - lint
  - test

include:
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml

### Base images
.node:
  image: node:20-alpine
  cache:
    - key:
        files:
          - package-lock.json
        prefix: node
      paths:
        - node_modules/

.php:
  image: php:8.2-alpine
  cache:
    - key:
        files:
          - composer-lock.json
        prefix: composer
      paths:
        - vendor/

### Build stage
composer:
  extends: .php
  stage: build
  before_script:
    - EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
    - test "$EXPECTED_CHECKSUM" == "$ACTUAL_CHECKSUM"
    - php composer-setup.php
  script:
    - php composer.phar install --ignore-platform-reqs

node:
  extends: .node
  stage: build
  before_script:
    - apk add --no-cache git
  script:
    - npm ci

### Lint stage
commitlint:
  extends: .node
  stage: lint
  script:
    - npx --no -- commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA
  rules:
    - if: $CI_MERGE_REQUEST_DIFF_BASE_SHA

eslint:
  extends: .node
  stage: lint
  script:
    - npx --no -- eslint resources/js/**/*.{js,ts,vue}

phpcs:
  extends: .php
  stage: lint
  script:
    - vendor/bin/phpcs

prettier:
  extends: .node
  stage: lint
  image: node:20-alpine
  script:
    - npx --no -- prettier --list-different resources/js resources/sass

rector:
  extends: .php
  stage: lint
  before_script:
    - apk add --no-cache git
  script:
    - vendor/bin/rector process
    - git diff --exit-code

stylelint:
  extends: .node
  stage: lint
  script:
    - npx --no -- stylelint resources/{js,sass}/**/*.{css,sass,vue}

### Test stage
dusk:
  stage: test
  image: docker:26-cli
  services:
    - docker:26-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
    - cp .env.dusk.compose .env
  script:
    - docker compose --file docker-compose.testing.yml up --abort-on-container-exit --exit-code-from dusk --attach dusk
