# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - lint
  - test
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
sast:
  stage: test
include:
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
commitlint:
  stage: lint
  image: node:alpine
  before_script:
    - apk add --no-cache git
    - npm ci
  script:
    - npx --no -- commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA
  rules:
    - if: $CI_MERGE_REQUEST_DIFF_BASE_SHA
eslint:
  stage: lint
  image: node:alpine
  before_script:
    - apk add --no-cache git
    - npm ci
  script:
    - npx --no -- eslint resources/js/**/*.{js,ts,vue}
prettier:
  stage: lint
  image: node:alpine
  before_script:
    - apk add --no-cache git
    - npm ci
  script:
    - npx --no -- prettier --list-different resources/js resources/sass
stylelint:
  stage: lint
  image: node:alpine
  before_script:
    - apk add --no-cache git
    - npm ci
  script:
    - npx --no -- stylelint resources/{js,sass}/**/*.{css,sass,vue}
dusk:
  stage: test
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
    - cp .env.dusk.compose .env
  script:
    - docker compose --file docker-compose.testing.yml up --abort-on-container-exit --exit-code-from dusk --attach dusk
