"*.{css,js,ts,vue}":
  - "prettier --check"

"*.{js,ts,vue}":
  - "eslint"

"*.{css,vue}":
  - "stylelint"

"*.php":
  - vendor/bin/pint --silent --test
  - vendor/bin/rector --dry-run --no-progress-bar
