version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./container-start
        working_dir: /roomz
        environment:
            DB_HOST: 'mariadb'
            MAIL_HOST: 'mailpit'
            PUSHER_HOST: 'soketi'
            VITE_PUSHER_HOST: '${APP_HOST}'
            VITE_PUSHER_PORT: '${PUSHER_PORT}'
        ports:
            - '${APP_PORT:-8000}:${APP_PORT:-8000}'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/roomz:z'
        networks:
            - roomz
        depends_on:
            - mariadb
            - mailpit
            - soketi
    mariadb:
        image: 'docker.io/library/mariadb:10'
        ports:
            - '${DB_PORT:-3306}:${DB_PORT:-3306}'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'roomz-mariadb:/var/lib/mysql'
        networks:
            - roomz
    mailpit:
        image: 'docker.io/axllent/mailpit:latest'
        ports:
            - '${MAIL_PORT:-1025}:${MAIL_PORT:-1025}'
            - '${MAILPIT_DASHBOARD_PORT:-8025}:${MAILPIT_DASHBOARD_PORT:-8025}'
        networks:
            - roomz
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_PORT: '${PUSHER_PORT:-6001}'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:${PUSHER_PORT:-6001}'
        networks:
            - roomz
networks:
    roomz:
        driver: bridge
volumes:
    roomz-mariadb:
        driver: local
