---
x-environment: &env
  DB_HOST: mariadb
  MAIL_HOST: mailpit
  REDIS_HOST: redis
  REVERB_HOST: reverb

services:
  php-fpm:
    build:
      target: php-fpm
      secrets:
        - .env
    volumes:
      - php-fpm-socket:/var/run/php
      - .docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - .env:/var/www/.env
    depends_on:
      - mariadb
      - redis
    environment:
      <<: *env
    restart: unless-stopped
  queue-worker:
    extends: php-fpm
    command: php artisan queue:work
  schedule-worker:
    extends: php-fpm
    command: php artisan schedule:work
  reverb:
    extends: php-fpm
    command: php artisan reverb:start --host=0.0.0.0
  caddy:
    build:
      target: caddy
      secrets:
        - .env
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - php-fpm-socket:/var/run/php
      - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - php-fpm
      - queue-worker
      - schedule-worker
      - reverb
    environment:
      <<: *env
      APP_SCHEME: $APP_SCHEME
      APP_HOST: $APP_HOST
      APP_PORT: $APP_PORT
  mariadb:
    image: mariadb:10
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_DATABASE: $DB_DATABASE
      MARIADB_USER: $DB_USERNAME
      MARIADB_PASSWORD: $DB_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql
      - .docker/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # ports:
    #   - 3306:3306
  redis:
    image: redis:7
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
  mailpit:
    image: axllent/mailpit
    environment:
      MP_DATABASE: /data/mailpit.db
    ports:
      # - 1025:1025
      - 8025:8025
    volumes:
      - mailpit-data:/data
    healthcheck:
      disable: true
volumes:
  caddy-config:
  caddy-data:
  mailpit-data:
  mariadb-data:
  php-fpm-socket:
  redis-data:
secrets:
  .env:
    file: .env
