version: "0.5"

processes:
  app:reload:
    disabled: true
    command: "php artisan serve"
  app:workers:
    command: "php artisan serve --no-reload"
    environment:
      - "PHP_CLI_SERVER_WORKERS=8"

  services:
    command: "docker compose up --detach --wait mailpit mariadb redis"

  reverb:
    command: "php artisan reverb:start"
    depends_on: &depends_on_services
      services:
        condition: process_completed_successfully

  vite:build:
    command: "npm run build"
  vite:dev:
    disabled: true
    command: "npm run dev"

  queue:work:
    disabled: true
    command: "php artisan queue:work"
    depends_on: *depends_on_services
  schedule:work:
    disabled: true
    command: "php artisan schedule:work"
    depends_on: *depends_on_services
