<?php

namespace App\Services\Permissions;

use App\Enums\PermissionKey;
use Illuminate\Filesystem\Filesystem;

final readonly class TypeScriptPermissionGenerator
{
    public function __construct(private Filesystem $files) {}

    public function targetPath(): string
    {
        return resource_path('js/Types/PermissionKey.generated.ts');
    }

    public function generate(): string
    {
        $cases = collect(PermissionKey::cases());
        $entries = $cases
            ->map(fn (PermissionKey $permission): string => "    {$permission->name}: \"{$permission->value}\",")
            ->implode("\n");

        return <<<TYPESCRIPT
// Generated by `php artisan roomz:generate-permission-types`. Do not edit manually.
export const PermissionKey = {
{$entries}
} as const;

export type PermissionKey = (typeof PermissionKey)[keyof typeof PermissionKey];

TYPESCRIPT;
    }

    public function isCurrent(): bool
    {
        return $this->files->exists($this->targetPath())
            && $this->files->get($this->targetPath()) === $this->generate();
    }

    public function write(): bool
    {
        if ($this->isCurrent()) {
            return false;
        }

        $this->files->put($this->targetPath(), $this->generate());

        return true;
    }
}
