#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if from=$(git rev-parse --abbrev-ref '@{push}'); then
    to=$(git rev-parse --abbrev-ref HEAD)
fi

if [ "$from" ] && [ "$to" = main ]; then
    node_modules/.bin/commitlint --from="$from" --to="$to"
fi

vendor/bin/phpstan --no-progress
vendor/bin/pint --silent --test
vendor/bin/rector --dry-run --no-progress-bar
