# Included from .gitlab-ci.yml.
### Automation stage
dependabot:
  stage: automation
  image: ${DOCKERHUB_IMAGE_PREFIX}alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
  script:
    - apk add --no-cache curl jq
    - scripts/dependabot-merge-request.sh
    - scripts/prune-mirror-branches.sh
    - scripts/stale-pull-requests.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH =~ /^dependabot\/.*/
